<a href="https://colab.research.google.com/github/lathamithu/Basics_of_ML/blob/master/Python%20basics%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
data = pd.read_csv('50_Startups.csv')

In [0]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [0]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
print (x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [0]:
print (y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [0]:
x[0,:]

array([165349.2, 136897.8, 471784.1, 'New York'], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [0]:
lEncoder = LabelEncoder()
lEncoder.fit(x[:,3])

LabelEncoder()

In [0]:
lEncoder.classes_

array([0, 1, 2], dtype=object)

In [0]:
lEncoder.transform(['Florida'])

In [0]:
x[0]

array([165349.2, 136897.8, 471784.1, 2], dtype=object)

In [0]:
x[:,3] = lEncoder.transform(x[:,3])

In [0]:
x[0]

array([165349.2, 136897.8, 471784.1, 2], dtype=object)

In [0]:
ohEncoder = OneHotEncoder(categorical_features=[3])

TypeError: ignored

In [0]:
x[0]

array([165349.2, 136897.8, 471784.1, 2], dtype=object)

In [0]:
x = x[:,1:]

In [0]:
x[0]

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/5)

In [0]:
from sklearn.linear_model import LinearRegression
mRegressor = LinearRegression()
mRegressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
y_predict = mRegressor.predict(x_test)

In [0]:
y_predict

array([104202.08075494, 114423.43184639,  87226.76844871,  49955.44164876,
       135780.5125985 ,  66019.69176888,  98692.76281982, 129229.97533138,
       190150.08727073,  45774.15052784])

In [0]:
y_test

array([107404.34, 110352.25,  96479.51,  14681.4 , 144259.4 ,  81229.06,
        99937.59, 134307.35, 192261.83,  64926.08])

In [0]:
mRegressor.score(x_test,y_test)

0.8994587271553415

In [0]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix